import argparse
import os
import pandas as pd


TIME_COLUMNS = ['admittime', 'dischtime']

#final dataframe: 
def finalize_merged_frames(merged_df: pd.DataFrame, save=False) -> pd.DataFrame:
    """
    Mainly dropping rows, which don't have ICD-10 codes and then clean-up and rearranging of the tables.
    
    :param merged_df: Dataframe generated by the load_and_merge_notes function
    :type merged_df: pd.DataFrame
    :return: Cleaned up dataframe
    :rtype: DataFrame
    """
    finalized_df = merged_df.dropna(subset=['note_id', 'text'])
    cols_to_keep = ['note_id', 'text', 'hadm_id','subject_id', 'icd_code']
    finalized_df = finalized_df[cols_to_keep]
    finalized_df = finalized_df.rename(columns={'note_id': 'report_id', 'text' : 'report_txt', 'icd_code' : 'y_true'})
    finalized_df = finalized_df[['report_id', 'report_txt', 'hadm_id', 'subject_id', 'y_true']]
    return finalized_df 



# notes merge with processed admissions
def load_and_merge_notes(data_dir: dir, dia: pd.DataFrame) -> pd.DataFrame:
    """
    load notes from data directory, process it and merge with admissions dataframes
    :param data_dir: data directory with "mimic" folder inside
    :type data_dir: dir
    :param adm_dia: admissions dataframe with diagnostic codes added and aggregated
    :type adm_dia: pd.DataFrames
    :return: Merged dataframe with notes and diagnoses
    :rtype: DataFrame
    """

    notes = pd.read_csv(data_dir + "/mimic/" + "discharge.csv.gz")
    filtered_notes = filter_notes(notes)
    merged_df = pd.merge(dia, filtered_notes, on=['hadm_id', 'subject_id'], how='left')
    print(merged_df.info())
    return merged_df


# notes cleaner + filterer 
def filter_notes(notes_df: pd.DataFrame, admission_text_only=False) -> pd.DataFrame:
    """
    Keep only Discharge Summaries and filter out Newborn admissions. Replace duplicates and join reports with
    their addendums. If admission_text_only is True, filter all sections that are not known at admission time.
    """
    # strip texts from leading and trailing and white spaces
    notes_df["text"] = notes_df["text"].str.strip()

    # remove entries without subject id or text
    notes_df = notes_df.dropna(subset=["subject_id", "text"])

    if admission_text_only:
        # reduce text to admission-only text
        notes_df = filter_admission_text(notes_df)

    return notes_df


def filter_admission_text(notes_df: pd.DataFrame) -> pd.DataFrame:
    """
    Filter text information by section and only keep sections that are known on admission time.
    """
    admission_sections = {
        "chief_complaint": "chief complaint:",
        "present_illness": "present illness:",
        "medical_history": "medical history:",
        "medication_adm": "medications on admission:",
        "allergies": "allergies:",
        "physical_exam": "physical exam:",
        "family_history": "family history:",
        "social_history": "social history:"
    }

    # replace linebreak indicators
    # notes_df['text'] = notes_df['text'].str.replace("\n", "\\n")
    notes_df['text'] = notes_df['text'].str.replace("___\nFamily History:", "___\n\nFamily History:", flags=re.IGNORECASE)

    # extract each section by regex
    for key, section in admission_sections.items():
        notes_df[key] = notes_df.text.str.extract('{}([\\s\\S]+?)\n\\s*?\n[^(\\\\|\\d|\\.)]+?:'.format(section), flags=re.IGNORECASE)

        notes_df[key] = notes_df[key].str.replace('\n', ' ')
        notes_df[key] = notes_df[key].str.strip()
        notes_df[key] = notes_df[key].fillna("")
        notes_df.loc[notes_df[key].str.startswith("[]"), key] = ""

    # filter notes with missing main information
    notes_df = notes_df[(notes_df.chief_complaint != "") | (notes_df.present_illness != "") |
                        (notes_df.medical_history != "")]

    # add section headers and combine into TEXT_ADMISSION
    notes_df = notes_df.assign(text="CHIEF COMPLAINT: " + notes_df.chief_complaint.astype(str)
                                    + '\n\n' +
                                    "PRESENT ILLNESS: " + notes_df.present_illness.astype(str)
                                    + '\n\n' +
                                    "MEDICAL HISTORY: " + notes_df.medical_history.astype(str)
                                    + '\n\n' +
                                    "MEDICATION ON ADMISSION: " + notes_df.medication_adm.astype(str)
                                    + '\n\n' +
                                    "ALLERGIES: " + notes_df.allergies.astype(str)
                                    + '\n\n' +
                                    "PHYSICAL EXAM: " + notes_df.physical_exam.astype(str)
                                    + '\n\n' +
                                    "FAMILY HISTORY: " + notes_df.family_history.astype(str)
                                    + '\n\n' +
                                    "SOCIAL HISTORY: " + notes_df.social_history.astype(str))['text']

    return notes_df


def load_diagnoses(data_dir: dir) -> pd.DataFrame:
    """
    Load the diagnostics table and perform cleaning and aggregation/grouping
    
    :param data_dir: data directory, contianing a folder named mimic (with diagnoses data inside)
    :type data_dir: dir
    :return: Dataframe with ICD-9 rows dropped and the rest grouped by hadm_id
    :rtype: DataFrame
    """
    full_dir = data_dir + "/mimic/diagnoses_icd.csv.gz"
    dia = pd.read_csv(full_dir)
    dia = dia[dia['icd_version'] != 9]
    
    # Format ICD-10 codes to proper format (letter + 2 digits . remaining)
    dia['icd_code'] = dia['icd_code'].apply(lambda x: x[:3] + '.' + x[3:] if pd.notna(x) and len(x) > 3 else x)

    dia = dia \
        .dropna() \
        .groupby(['hadm_id', 'subject_id']) \
        .agg(set) \
        .reset_index()

    print(dia.info())
    return dia

def main():
    parser = argparse.ArgumentParser(description="Location of the data directory (must contain a folder titled mimic, with admissions, diagnoses and discharge csv files from MIMIC-IV)")
    parser.add_argument(
        "data_dir",
        type=str,
        help="Path to the data directory"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory (default: same as data_dir)"
    )
    parser.add_argument(
        "--limit",
        "--l",
        type=int,
        default=None,
        help="No of rows to read from the dataset (default: read the entire csv files)"
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose output"

    )
    
    args = parser.parse_args()
    
    if not os.path.isdir(args.data_dir):
        parser.error(f"Data directory does not exist: {args.data_dir}")
    
    output_dir = args.output_dir or args.data_dir
    os.makedirs(output_dir, exist_ok=True)
    
    if args.verbose:
        print(f"Data directory: {args.data_dir}")
        print(f"Output directory: {output_dir}")



if __name__ == "__main__":
    main()